DROP TABLE IF EXISTS markets;
CREATE TABLE markets (
FMID VARCHAR(10) NOT NULL,
street VARCHAR(100) NOT NULL,
street VARCHAR(100) NULL,
city VARCHAR(50) NULL,
County VARCHAR(50) NULL,
State VARCHAR(50) NULL,
zip VARCHAR(10) NULL,
x NUMERIC(12) NOT NULL,
y NUMERIC(12) NOT NULL
);

DROP TABLE IF EXISTS paymentTypes;
CREATE TABLE paymentTypes (
FMID VARCHAR(10) NOT NULL,
Credit VARCHAR(1) NULL,
WIC VARCHAR(1) NULL,
WICcash VARCHAR(1) NULL,
SFMNP VARCHAR(1) NULL,
SNAP VARCHAR(1) NULL
);

DROP TABLE IF EXISTS products;
CREATE TABLE products (
FMID VARCHAR(10) NOT NULL,
Organic VARCHAR(1) NULL,
Bakedgoods VARCHAR(1) NULL,
Cheese VARCHAR(1) NULL,
Crafts VARCHAR(1) NULL,
Flowers VARCHAR(1) NULL,
Eggs VARCHAR(1) NULL,
Seafood VARCHAR(1) NULL,
Herbs VARCHAR(1) NULL,
Vegetables VARCHAR(1) NULL,
Honey VARCHAR(1) NULL,
Jams VARCHAR(1) NULL,
Maple VARCHAR(1) NULL,
Meat VARCHAR(1) NULL,
Nursery VARCHAR(1) NULL,
Nuts VARCHAR(1) NULL,
Plants VARCHAR(1) NULL,
Poultry VARCHAR(1) NULL,
Prepared VARCHAR(1) NULL,
Soap VARCHAR(1) NULL,
Trees VARCHAR(1) NULL,
Wine VARCHAR(1) NULL,
Coffee VARCHAR(1) NULL,
Beans VARCHAR(1) NULL,
Fruits VARCHAR(1) NULL,
Grains VARCHAR(1) NULL,
Juices VARCHAR(1) NULL,
Mushrooms VARCHAR(1) NULL,
PetFood VARCHAR(1) NULL,
Tofu VARCHAR(1) NULL,
WildHarvested VARCHAR(1) NULL
);

DROP TABLE IF EXISTS socialMedia;
CREATE TABLE socialMedia (
FMID VARCHAR(10) NOT NULL,
Website VARCHAR(256) NULL,
Facebook VARCHAR(256) NULL,
Twitter VARCHAR(256) NULL,
Youtube VARCHAR(256) NULL,
OtherMedia VARCHAR(256) NULL
);

DROP TABLE IF EXISTS schedule;
CREATE TABLE schedule (
FMID VARCHAR(10) NOT NULL,
season VARCHAR(50) NULL,
seasonOpenning VARCHAR(50) NULL,
seasonClosing VARCHAR(50) NULL,
seasonTime VARCHAR(100) NOT NULL
);